// <auto-generated />
using System;
using Films.DAL.MsSqlServer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Films.DAL.MsSqlServer.Migrations
{
    [DbContext(typeof(FilmsDbContext))]
    partial class FilmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActorBirthday")
                        .HasColumnType("date");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("ActorId");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorBirthday = new DateTime(1952, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Liam Neeson"
                        },
                        new
                        {
                            ActorId = 2,
                            ActorBirthday = new DateTime(1971, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Ewan McGregor"
                        },
                        new
                        {
                            ActorId = 3,
                            ActorBirthday = new DateTime(1981, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Natalie Portman"
                        },
                        new
                        {
                            ActorId = 4,
                            ActorBirthday = new DateTime(1989, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Jake Lloyd"
                        },
                        new
                        {
                            ActorId = 5,
                            ActorBirthday = new DateTime(1948, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Samuel L. Jackson"
                        },
                        new
                        {
                            ActorId = 6,
                            ActorBirthday = new DateTime(1944, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Frank Oz"
                        },
                        new
                        {
                            ActorId = 7,
                            ActorBirthday = new DateTime(1944, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Ian McDiarmid"
                        },
                        new
                        {
                            ActorId = 8,
                            ActorBirthday = new DateTime(1951, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Mark Hamill"
                        },
                        new
                        {
                            ActorId = 9,
                            ActorBirthday = new DateTime(1942, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Harrison Ford"
                        },
                        new
                        {
                            ActorId = 10,
                            ActorBirthday = new DateTime(1956, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Carrie Fisher"
                        },
                        new
                        {
                            ActorId = 11,
                            ActorBirthday = new DateTime(1914, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Alec Guinness"
                        },
                        new
                        {
                            ActorId = 12,
                            ActorBirthday = new DateTime(1944, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Peter Mayhew"
                        },
                        new
                        {
                            ActorId = 13,
                            ActorBirthday = new DateTime(1935, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "David Prowse"
                        },
                        new
                        {
                            ActorId = 14,
                            ActorBirthday = new DateTime(1945, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Jeremy Bulloch"
                        },
                        new
                        {
                            ActorId = 15,
                            ActorBirthday = new DateTime(1983, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Adam Driver"
                        },
                        new
                        {
                            ActorId = 16,
                            ActorBirthday = new DateTime(1992, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Daisy Ridley"
                        },
                        new
                        {
                            ActorId = 17,
                            ActorBirthday = new DateTime(1992, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "John Boyega"
                        },
                        new
                        {
                            ActorId = 18,
                            ActorBirthday = new DateTime(1935, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Vasily Livanov"
                        },
                        new
                        {
                            ActorId = 19,
                            ActorBirthday = new DateTime(1941, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Vitaly Solomin"
                        },
                        new
                        {
                            ActorId = 20,
                            ActorBirthday = new DateTime(1901, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActorName = "Rina Zelyonaya"
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FilmDate")
                        .HasColumnType("date");

                    b.Property<string>("FilmDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("FilmId");

                    b.ToTable("Film");

                    b.HasData(
                        new
                        {
                            FilmId = 2,
                            FilmDate = new DateTime(1999, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "After a millennia, an ancient evil returns seeking revenge. Meanwhile, Jedi Knight Qui-Gon Jinn discovers Anakin Skywalker: a young slave boy unusually strong with the Force.",
                            FilmName = "Star Wars: The Phantom Menace"
                        },
                        new
                        {
                            FilmId = 3,
                            FilmDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.",
                            FilmName = "Star Wars: Attack of the Clones "
                        },
                        new
                        {
                            FilmId = 4,
                            FilmDate = new DateTime(2005, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "The evil Darth Sidious enacts his final plan for unlimited power -- and the heroic Jedi Anakin Skywalker must choose a side.",
                            FilmName = "Star Wars: Revenge of the Sith"
                        },
                        new
                        {
                            FilmId = 5,
                            FilmDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "With the planet-destroying power of the Death Star, the Empire looks to cement its grip on the galaxy. Meanwhile, farm boy Luke Skywalker rises to face his destiny.",
                            FilmName = "Star Wars: A New Hope"
                        },
                        new
                        {
                            FilmId = 6,
                            FilmDate = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "While the Death Star has been destroyed, the battle between the Empire and the Rebel Alliance rages on...and the evil Darth Vader continues his relentless search for Luke Skywalker.",
                            FilmName = "Star Wars: The Empire Strikes Back"
                        },
                        new
                        {
                            FilmId = 7,
                            FilmDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "Luke Skywalker leads a mission to rescue his friend Han Solo from the clutches of Jabba the Hutt, while the Emperor seeks to destroy the Rebellion once and for all with a second dreaded Death Star.",
                            FilmName = "Star Wars: Return of the Jedi"
                        },
                        new
                        {
                            FilmId = 8,
                            FilmDate = new DateTime(2015, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "Thirty years after the Battle of Endor, a new threat has risen in the form of the First Order and the villainous Kylo Ren. Meanwhile, Rey, a young scavenger, discovers powers that will change her life -- and possibly save the galaxy.",
                            FilmName = "Star Wars: The Force Awakens"
                        },
                        new
                        {
                            FilmId = 10,
                            FilmDate = new DateTime(1980, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmDescription = "A cycle of Soviet television films from 1979-1986 directed by Igor Maslennikov, a film adaptation of the works of Arthur Conan Doyle about Sherlock Holmes. The cycle consists of five films (11 episodes with a total duration of 766 minutes},.",
                            FilmName = "Sherlock Holmes and Doctor Watson"
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.FilmActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmActor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            FilmId = 2
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            FilmId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 3,
                            FilmId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 4,
                            FilmId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 6,
                            FilmId = 2
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 2,
                            FilmId = 3
                        },
                        new
                        {
                            Id = 7,
                            ActorId = 3,
                            FilmId = 3
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 5,
                            FilmId = 3
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 6,
                            FilmId = 3
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 7,
                            FilmId = 3
                        },
                        new
                        {
                            Id = 11,
                            ActorId = 2,
                            FilmId = 4
                        },
                        new
                        {
                            Id = 12,
                            ActorId = 3,
                            FilmId = 4
                        },
                        new
                        {
                            Id = 13,
                            ActorId = 7,
                            FilmId = 4
                        },
                        new
                        {
                            Id = 14,
                            ActorId = 5,
                            FilmId = 4
                        },
                        new
                        {
                            Id = 15,
                            ActorId = 8,
                            FilmId = 5
                        },
                        new
                        {
                            Id = 16,
                            ActorId = 9,
                            FilmId = 5
                        },
                        new
                        {
                            Id = 17,
                            ActorId = 10,
                            FilmId = 5
                        },
                        new
                        {
                            Id = 18,
                            ActorId = 13,
                            FilmId = 5
                        },
                        new
                        {
                            Id = 20,
                            ActorId = 8,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 21,
                            ActorId = 9,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 22,
                            ActorId = 10,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 23,
                            ActorId = 13,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 24,
                            ActorId = 6,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 25,
                            ActorId = 8,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 19,
                            ActorId = 6,
                            FilmId = 6
                        },
                        new
                        {
                            Id = 26,
                            ActorId = 9,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 27,
                            ActorId = 10,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 28,
                            ActorId = 7,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 29,
                            ActorId = 6,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 30,
                            ActorId = 13,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 31,
                            ActorId = 11,
                            FilmId = 7
                        },
                        new
                        {
                            Id = 32,
                            ActorId = 8,
                            FilmId = 8
                        },
                        new
                        {
                            Id = 33,
                            ActorId = 9,
                            FilmId = 8
                        },
                        new
                        {
                            Id = 34,
                            ActorId = 10,
                            FilmId = 8
                        },
                        new
                        {
                            Id = 35,
                            ActorId = 15,
                            FilmId = 8
                        },
                        new
                        {
                            Id = 36,
                            ActorId = 16,
                            FilmId = 8
                        },
                        new
                        {
                            Id = 38,
                            ActorId = 18,
                            FilmId = 10
                        },
                        new
                        {
                            Id = 39,
                            ActorId = 19,
                            FilmId = 10
                        },
                        new
                        {
                            Id = 40,
                            ActorId = 20,
                            FilmId = 10
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.FilmGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 4,
                            FilmId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 5,
                            FilmId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 6,
                            FilmId = 2,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 7,
                            FilmId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 8,
                            FilmId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 9,
                            FilmId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 10,
                            FilmId = 3,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 11,
                            FilmId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 12,
                            FilmId = 3,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 13,
                            FilmId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 14,
                            FilmId = 3,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 15,
                            FilmId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 16,
                            FilmId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 17,
                            FilmId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 18,
                            FilmId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 19,
                            FilmId = 4,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 20,
                            FilmId = 4,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 21,
                            FilmId = 4,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 22,
                            FilmId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 23,
                            FilmId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 24,
                            FilmId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 25,
                            FilmId = 5,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 26,
                            FilmId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 27,
                            FilmId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 28,
                            FilmId = 5,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 29,
                            FilmId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 30,
                            FilmId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 31,
                            FilmId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 32,
                            FilmId = 6,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 33,
                            FilmId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 34,
                            FilmId = 6,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 35,
                            FilmId = 6,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 36,
                            FilmId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 37,
                            FilmId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 38,
                            FilmId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 39,
                            FilmId = 7,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 40,
                            FilmId = 7,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 41,
                            FilmId = 7,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 42,
                            FilmId = 7,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 43,
                            FilmId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 44,
                            FilmId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 45,
                            FilmId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 46,
                            FilmId = 8,
                            GenreId = 4
                        },
                        new
                        {
                            Id = 47,
                            FilmId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            Id = 48,
                            FilmId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            Id = 49,
                            FilmId = 8,
                            GenreId = 7
                        },
                        new
                        {
                            Id = 50,
                            FilmId = 10,
                            GenreId = 3
                        },
                        new
                        {
                            Id = 51,
                            FilmId = 10,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(48)")
                        .HasMaxLength(48);

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Science fiction"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Film epic"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Detective film"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Action movie"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Adventures"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Space opera"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Fantasy"
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("PhotoId");

                    b.HasIndex("FilmId");

                    b.ToTable("Photo");

                    b.HasData(
                        new
                        {
                            PhotoId = 1,
                            FilmId = 2,
                            PhotoPath = "Star Wars - The Phantom Menace.webp"
                        },
                        new
                        {
                            PhotoId = 2,
                            FilmId = 3,
                            PhotoPath = "Star Wars - Attack of the Clones.webp"
                        },
                        new
                        {
                            PhotoId = 3,
                            FilmId = 4,
                            PhotoPath = "Star Wars - Revenge of the Sith.jpeg"
                        },
                        new
                        {
                            PhotoId = 4,
                            FilmId = 5,
                            PhotoPath = "Star Wars - A New Hope.webp"
                        },
                        new
                        {
                            PhotoId = 5,
                            FilmId = 6,
                            PhotoPath = "Star Wars - The Empire Strikes Back.jpeg"
                        },
                        new
                        {
                            PhotoId = 6,
                            FilmId = 7,
                            PhotoPath = "Star Wars - Return of the Jedi.jpeg"
                        },
                        new
                        {
                            PhotoId = 7,
                            FilmId = 8,
                            PhotoPath = "Star Wars - The Force Awakens.webp"
                        },
                        new
                        {
                            PhotoId = 8,
                            FilmId = 10,
                            PhotoPath = "Sherlock Holmes and Doctor Watson.jpg"
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("RatingId");

                    b.HasIndex("FilmId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            RatingId = 10,
                            FilmId = 8,
                            UserEmail = "admin@gmail.com"
                        },
                        new
                        {
                            RatingId = 12,
                            FilmId = 6,
                            UserEmail = "admin@gmail.com"
                        },
                        new
                        {
                            RatingId = 13,
                            FilmId = 2,
                            UserEmail = "vasya@gmail.com"
                        },
                        new
                        {
                            RatingId = 15,
                            FilmId = 3,
                            UserEmail = "vasya@gmail.com"
                        });
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.FilmActor", b =>
                {
                    b.HasOne("Films.DAL.MsSqlServer.Models.Actor", "Actor")
                        .WithMany("FilmActor")
                        .HasForeignKey("ActorId")
                        .HasConstraintName("FK__FilmActor__Actor__3D5E1FD2")
                        .IsRequired();

                    b.HasOne("Films.DAL.MsSqlServer.Models.Film", "Film")
                        .WithMany("FilmActor")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK__FilmActor__FilmI__3C69FB99")
                        .IsRequired();
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.FilmGenre", b =>
                {
                    b.HasOne("Films.DAL.MsSqlServer.Models.Film", "Film")
                        .WithMany("FilmGenre")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK__FilmGenre__FilmI__5DCAEF64")
                        .IsRequired();

                    b.HasOne("Films.DAL.MsSqlServer.Models.Genre", "Genre")
                        .WithMany("FilmGenre")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK__FilmGenre__Genre__5CD6CB2B")
                        .IsRequired();
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Photo", b =>
                {
                    b.HasOne("Films.DAL.MsSqlServer.Models.Film", "Film")
                        .WithMany("Photo")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK__Photo__FilmId__49C3F6B7")
                        .IsRequired();
                });

            modelBuilder.Entity("Films.DAL.MsSqlServer.Models.Rating", b =>
                {
                    b.HasOne("Films.DAL.MsSqlServer.Models.Film", "Film")
                        .WithMany("Rating")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK__Rating__FilmId__2F10007B")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
